// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 22/6/2026 下午7:11:54
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/local-server/dsoba-mobile-demo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/local-server/dsoba-mobile-demo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/local-server/dsoba-mobile-demo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/local-server/dsoba-mobile-demo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/local-server/dsoba-mobile-demo/plugins/**/*.{js,ts,mjs}","C:/local-server/dsoba-mobile-demo/composables/**/*.{js,ts,mjs}","C:/local-server/dsoba-mobile-demo/utils/**/*.{js,ts,mjs}","C:/local-server/dsoba-mobile-demo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/local-server/dsoba-mobile-demo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/local-server/dsoba-mobile-demo/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;